### ISSUE TITLE
What about parameters?

### ISSUE THREAD

**Issue by umpirsky** [mlabouardy/swaggymnia#2]
I have a postman collection, and have requests like `/profile/umpirsky` in it, where `umpirsky` is `username` parameter. Concrete value for parameters is what is expected in postman collections.

I export this, and import in Insomnia, then export from there and use swaggyermania to export it to swagger UI format. But then I have no parameters in swagger UI.

How do you usually manage this? Keep `/profile/{username}` placeholders in Insomnia? What about paremeter type, description...?

Thanks for the nice tool!

**Comment by mlabouardy** [comment]
Keep /profile/{username} placeholders in Insomnia

At this moment, the tool doesnt support parameter type & description, but im working on it :)
