### ISSUE TITLE
Even if config is saying scheme "http", swaggymnia generates file as "https"

### ISSUE THREAD

**Issue by rogeriopradoj** [mlabouardy/swaggymnia#4]
### Expected behavior

Should respect config file about scheme definition. If we define "http" as scheme, swaggymnia should generate file as "http".

### Current behavior

swaggymnia is generating file as "https" doesn't matter if we setup config with "http"

### Steps to reproduce the behavior

```
swaggymnia generate -i INSOMNIA.json -c CONFIG.json
```

CONFIG.json is:

```json
{
    "title": "API TITLE",
    "version": "0",
    "host": "example.com",
    "bastPath": "/path/to/resources",
    "schemes": "http",
    "description": "API DESCRIPTION"
}
```

**Comment by mlabouardy** [comment]
it has been fixed :) 

thank you for your feedback

**Comment by rogeriopradoj** [comment]
@mlabouardy my pleasure ;-)

**Comment by dardox** [comment]
It does not work at all. Whatever I do shows this
panic: assignment to entry in nil map

goroutine 1 [running]:
main.parse(0xc420012b80, 0x6, 0x3, 0xed21616c2, 0x2756cd00, 0x0, 0xc42000b020, 0x1c, 0xc42011c000, 0xa, ...)
	C:/Users/Mohamed/go/src/github.com/mlabouardy/swaggymnia/swagger.go:51 +0x32c
main.(*Swagger).Generate(0xc4201197d8, 0x7ffca03811e1, 0x1d, 0x7ffca0381202, 0x9, 0x5f8620, 0x4)
	C:/Users/Mohamed/go/src/github.com/mlabouardy/swaggymnia/swagger.go:83 +0x11f
main.main.func1(0xc420088840, 0x100, 0xc420088840)
	C:/Users/Mohamed/go/src/github.com/mlabouardy/swaggymnia/app.go:57 +0x180
github.com/urfave/cli.HandleAction(0x5bd740, 0x608ba0, 0xc420088840, 0xc42000e400, 0x0)
	C:/Users/Mohamed/go/src/github.com/urfave/cli/app.go:502 +0xd4
github.com/urfave/cli.Command.Run(0x5fb2c0, 0x8, 0x0, 0x0, 0xc4200128e0, 0x1, 0x1, 0x602cf6, 0x1e, 0x0, ...)
	C:/Users/Mohamed/go/src/github.com/urfave/cli/command.go:210 +0xb87
github.com/urfave/cli.(*App).Run(0xc4200c41c0, 0xc42000e0c0, 0x6, 0x6, 0x0, 0x0)
	C:/Users/Mohamed/go/src/github.com/urfave/cli/app.go:259 +0x7b7
main.main()
	C:/Users/Mohamed/go/src/github.com/mlabouardy/swaggymnia/app.go:66 +0x515
No solution online...
